### ISSUE TITLE
Logo Proposal for Lemonad

### ISSUE THREAD

**Issue by area55git** [inputfalken/Lemonad#1]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project Lemonad.

I will be pleased to collaborate with you.

**Comment by inputfalken** [comment]
That could be nice,  let me know you have in mind! 😁

**Comment by area55git** [comment]
perfect, in two days I will be sending you a proposal.

**Comment by area55git** [comment]
Do you have any guidelines on how you would like the logo?

**Comment by inputfalken** [comment]
Hmm, maybe something like the C# logo mixed with the lambda letter.

**Comment by inputfalken** [comment]
How's it going with the Logo? 🙂

**Comment by area55git** [comment]
Hi @inputfalken I'm working on the sketches, sorry, I was a bit busy with other contributions. tomorrow I send you the proposals.

**Comment by area55git** [comment]
I send you 3 logo proposals, according to the indications this was the result, I hope you like it.

[![LOGO_PROPOSAL_FOR_LEMONAD.jpg](https://s8.postimg.cc/hqbn5klit/LOGO_PROPOSAL_FOR_LEMONAD.jpg)](https://postimg.cc/image/ifufhxm29/)

Remember that they are only sketches, you can suggest the changes you want

**Comment by inputfalken** [comment]
Would it be possible to make it darker with flat colors? 🙂

**Comment by area55git** [comment]
If possible, what proposal did you like to make the changes?

**Comment by inputfalken** [comment]
I like the first option. But I think it would look nicer with darker colors. 

Like `#2C3E50` and `#2c503b`.

**Comment by area55git** [comment]
[![LOGO_PROPOSAL_FOR_LEMONAD_2.jpg](https://s8.postimg.cc/6g7fufp2t/LOGO_PROPOSAL_FOR_LEMONAD_2.jpg)](https://postimg.cc/image/515v5pnzl/)


Hi @inputfalken 
Option 1 has the colors suggested by you, I think it looks very dark.
Although the blue color you chose, I see it great.
Option 2 and 3 I consider are the best because they have the light green color and this gives more contrast to the logo.

You decide which option you like.

**Comment by inputfalken** [comment]
I like option one 👍. I prefer distinct logos

**Comment by area55git** [comment]
Perfect, I will prepare the final files in PNG, SVG and others, I will also make a PR to place the logo in the Readme folder

**Comment by area55git** [comment]
Would you like this design for the README folder?

[![LOGO_LEMONAD_README_2.jpg](https://s8.postimg.cc/erma9qwol/LOGO_LEMONAD_README_2.jpg)](https://postimg.cc/image/6yvmhrqpd/)

**Comment by inputfalken** [comment]
Sure 👍

**Comment by area55git** [comment]
PR #28

**Comment by area55git** [comment]
I am very pleased to be able to collaborate in your project. 🙂

**Comment by inputfalken** [comment]
Thanks for your contribution! 😄
